import React from "react";
import { Link } from "wouter";
import { motion } from "framer-motion";
import { ArrowRight, ShieldCheck, Zap, Globe2, MessageSquare, Code } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function Home() {
  return (
    <div className="w-full flex flex-col items-center">
      {/* Hero Section */}
      <section className="w-full relative pt-20 pb-32 lg:pt-32 lg:pb-40 overflow-hidden flex flex-col items-center justify-center">
        {/* Background Image generated by AI */}
        <div className="absolute inset-0 z-0 opacity-40">
          <img 
            src={`${import.meta.env.BASE_URL}images/hero-bg.png`}
            alt="Hero abstract background"
            className="w-full h-full object-cover"
          />
          <div className="absolute inset-0 bg-gradient-to-b from-background/40 via-background/80 to-background"></div>
        </div>

        <div className="container max-w-7xl mx-auto px-4 relative z-10 text-center flex flex-col items-center">
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            transition={{ duration: 0.5, ease: "easeOut" }}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/5 border border-white/10 backdrop-blur-md mb-8 shadow-2xl"
          >
            <span className="flex h-2 w-2 rounded-full bg-accent animate-pulse"></span>
            <span className="text-sm font-medium text-white/80">Premium OTP Service</span>
          </motion.div>

          <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1, ease: "easeOut" }}
            className="text-5xl md:text-7xl lg:text-8xl font-display font-extrabold text-white tracking-tight max-w-4xl mx-auto leading-tight"
          >
            Virtual Numbers <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary via-blue-400 to-accent">
              Made Simple
            </span>
          </motion.h1>

          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2, ease: "easeOut" }}
            className="mt-8 text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed"
          >
            Get instant access to virtual numbers from over 180 countries. Receive SMS verification codes for Telegram, WhatsApp, Gmail, and hundreds of other services securely and anonymously.
          </motion.p>

          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.3, ease: "easeOut" }}
            className="mt-12 flex flex-col sm:flex-row items-center gap-4 w-full justify-center"
          >
            <Link href="/buy">
              <Button size="lg" className="w-full sm:w-auto h-14 px-8 rounded-xl text-lg font-semibold bg-primary hover:bg-primary/90 text-white shadow-xl shadow-primary/30 border border-primary/50 transition-all hover:-translate-y-1">
                Buy a Number Now
                <ArrowRight className="ml-2 w-5 h-5" />
              </Button>
            </Link>
            <Link href="/register">
              <Button size="lg" variant="outline" className="w-full sm:w-auto h-14 px-8 rounded-xl text-lg font-semibold border-white/20 bg-white/5 hover:bg-white/10 text-white backdrop-blur-md transition-all">
                Create Free Account
              </Button>
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section className="w-full py-24 bg-card/30 border-y border-white/5 relative">
        <div className="container max-w-7xl mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-display font-bold text-white mb-4">Why choose ZyNum?</h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">We provide the most reliable and fastest virtual number infrastructure on the market.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            <FeatureCard 
              icon={<Zap className="w-8 h-8 text-yellow-400" />}
              title="Instant Delivery"
              description="Numbers are provisioned instantly. Receive your OTP codes in seconds, not minutes."
              delay={0.1}
            />
            <FeatureCard 
              icon={<Globe2 className="w-8 h-8 text-blue-400" />}
              title="Global Coverage"
              description="Access to virtual numbers from over 180 countries worldwide. Local numbers for local services."
              delay={0.2}
            />
            <FeatureCard 
              icon={<ShieldCheck className="w-8 h-8 text-green-400" />}
              title="Secure & Private"
              description="Protect your personal identity. Never use your real phone number for online verifications again."
              delay={0.3}
            />
            <FeatureCard 
              icon={<MessageSquare className="w-8 h-8 text-purple-400" />}
              title="Hundreds of Services"
              description="Compatible with WhatsApp, Telegram, Google, Facebook, TikTok, and many more."
              delay={0.4}
            />
          </div>
        </div>
      </section>

      {/* API CTA Section */}
      <section className="w-full py-32 relative overflow-hidden">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-primary/10 blur-[120px] rounded-full pointer-events-none" />
        
        <div className="container max-w-5xl mx-auto px-4 text-center relative z-10">
          <div className="bg-card/50 backdrop-blur-xl border border-white/10 rounded-3xl p-8 md:p-16 shadow-2xl shadow-black/50">
            <h2 className="text-3xl md:text-5xl font-display font-bold text-white mb-6">Build with our Developer API</h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto mb-10">
              Integrate ZyNum's powerful virtual number provisioning directly into your own applications. Simple REST endpoints, comprehensive documentation, and reliable uptime.
            </p>
            <Link href="/api-docs">
              <Button size="lg" className="h-14 px-8 rounded-xl text-lg font-semibold bg-white text-black hover:bg-gray-200 shadow-xl transition-all">
                <Code className="mr-2 w-5 h-5" />
                View Documentation
              </Button>
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}

function FeatureCard({ icon, title, description, delay }: { icon: React.ReactNode, title: string, description: string, delay: number }) {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-100px" }}
      transition={{ duration: 0.5, delay }}
      className="bg-card/40 border border-white/10 rounded-2xl p-6 hover:bg-card/60 transition-colors group"
    >
      <div className="w-14 h-14 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 group-hover:scale-110 group-hover:bg-white/10 transition-all duration-300">
        {icon}
      </div>
      <h3 className="text-xl font-bold text-white mb-3">{title}</h3>
      <p className="text-muted-foreground leading-relaxed">{description}</p>
    </motion.div>
  );
}
